version: 0.2
# this needs setting up in AWS -> CodeBuild -> monitor repo via Webhooks (no CD as there's no delivery/artefact)
# the IAM role it will use needs access to AWS to create stuff..instances..new roles for avx..kms
# ...

phases:
  install:
    on-failure: ABORT
    commands:
      - echo "Commit ID - ${Commit_ID}"
      # Updates package repositories in image
      - apt-get -y -qq update
      # Installs Terraform version specified in CI/CD env variable. To hardcode a specific version, change the wget target.
      - echo "Installing Terraform..."
      - wget -q https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - cp terraform /usr/bin/terraform
      - echo "Terraform Version:"
      - terraform --version
  pre_build:
    on-failure: ABORT
    commands:
      # Initialize Terraform 
      - terraform init

  build:
    on-failure: ABORT
    commands:
      - echo "Launching PLAN & APPLY..."
      - terraform plan -no-color -out=tfplan && terraform apply -no-color -auto-approve=true tfplan;
  post_build:
    on-failure: ABORT
    commands:
      - echo "Post build phase..."
      - rm -rf .terraform terraform terraform_${TF_VERSION}_linux_amd64.zip
